const state={data:[],filtered:[],selected:new Set()};
const $=s=>document.querySelector(s);
const els={search:$("#search"),model:$("#model"),token:$("#token"),segmentation:$("#segmentation"),layer:$("#layer"),gallery:$("#gallery"),summary:$("#summary"),empty:$("#empty"),reset:$("#reset"),compareBar:$("#compareBar"),compareCount:$("#compareCount"),compareButton:$("#compareButton"),clearCompare:$("#clearCompare"),viewer:$("#viewer"),viewerImage:$("#viewerImage"),viewerTitle:$("#viewerTitle"),comparison:$("#comparison"),comparisonGrid:$("#comparisonGrid")};

function uniq(field){return [...new Set(state.data.map(x=>x[field]).filter(x=>x!==null&&x!==undefined&&x!==""))].sort((a,b)=>String(a).localeCompare(String(b),"fr",{numeric:true}))}
function fill(select,values){values.forEach(v=>{const o=document.createElement("option");o.value=String(v);o.textContent=String(v);select.append(o)})}
function searchable(x){return [x.title,x.filename,x.model,x.token,x.segmentation,x.layer].join(" ").toLowerCase()}
function apply(){const q=els.search.value.trim().toLowerCase();state.filtered=state.data.filter(x=>(!q||searchable(x).includes(q))&&(!els.model.value||x.model===els.model.value)&&(!els.token.value||x.token===els.token.value)&&(!els.segmentation.value||x.segmentation===els.segmentation.value)&&(!els.layer.value||String(x.layer)===els.layer.value));render()}
function render(){els.gallery.replaceChildren();state.filtered.forEach(x=>els.gallery.append(card(x)));els.summary.textContent=`${state.filtered.length} figure(s) sur ${state.data.length}`;els.empty.hidden=state.filtered.length!==0}
function card(x){const a=document.createElement("article");a.className="card";const b=document.createElement("button");b.className="image";b.innerHTML=`<img loading="lazy" src="${x.src}" alt="${x.title}">`;b.onclick=()=>openViewer(x);const body=document.createElement("div");body.className="card-body";const h=document.createElement("h2");h.textContent=x.title;const chips=document.createElement("div");chips.className="chips";[x.model,x.token,x.segmentation,x.layer===null?null:`Couche ${x.layer}`].filter(Boolean).forEach(v=>{const s=document.createElement("span");s.textContent=v;chips.append(s)});const actions=document.createElement("div");actions.className="card-actions";const label=document.createElement("label");const cb=document.createElement("input");cb.type="checkbox";cb.checked=state.selected.has(x.id);cb.onchange=()=>toggle(x,cb);label.append(cb,document.createTextNode(" Comparer"));const link=document.createElement("a");link.href=x.src;link.target="_blank";link.textContent="Image originale";actions.append(label,link);body.append(h,chips,actions);a.append(b,body);return a}
function toggle(x,cb){if(cb.checked){if(state.selected.size>=4){cb.checked=false;alert("Maximum : quatre figures.");return}state.selected.add(x.id)}else state.selected.delete(x.id);updateCompare()}
function updateCompare(){const n=state.selected.size;els.compareBar.hidden=n===0;els.compareCount.textContent=`${n} figure(s) sélectionnée(s)`;els.compareButton.disabled=n<2}
function openViewer(x){els.viewerImage.src=x.src;els.viewerImage.alt=x.title;els.viewerTitle.textContent=x.title;els.viewer.showModal()}
function openComparison(){els.comparisonGrid.replaceChildren();state.data.filter(x=>state.selected.has(x.id)).forEach(x=>{const a=document.createElement("article");a.innerHTML=`<img src="${x.src}" alt="${x.title}"><h3>${x.title}</h3>`;els.comparisonGrid.append(a)});els.comparison.showModal()}
function reset(){[els.search,els.model,els.token,els.segmentation,els.layer].forEach(e=>e.value="");apply()}
async function init(){try{const r=await fetch("data.json",{cache:"no-store"});if(!r.ok)throw new Error(r.status);state.data=await r.json();fill(els.model,uniq("model"));fill(els.token,uniq("token"));fill(els.segmentation,uniq("segmentation"));fill(els.layer,uniq("layer"));[els.search,els.model,els.token,els.segmentation,els.layer].forEach(e=>{e.addEventListener("input",apply);e.addEventListener("change",apply)});els.reset.onclick=reset;els.compareButton.onclick=openComparison;els.clearCompare.onclick=()=>{state.selected.clear();updateCompare();render()};$("#closeViewer").onclick=()=>els.viewer.close();$("#closeComparison").onclick=()=>els.comparison.close();render()}catch(e){console.error(e);els.summary.textContent="Erreur de chargement. Lancez un serveur HTTP local.";els.empty.hidden=false}}
init();
